server:
  port: 8999
  servlet:
    context-path: /yuni
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  application:
    name: yuni
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uuu_talk?serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: root
    database: 0
    timeout: 20000
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 2
        max-wait: 2000
project:
  swagger-ui-open: true
  workerId: 0
  dataCenterId: 0
  jwtTimeout: 43200
  jwtIssuer: pay_service
  jwtSecret: pay_service_2021

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2/log4j2.xml